### ISSUE TITLE
Add yarn script to bring up a local Chainlink Adapter for testing

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/turbo#820]
- Don't commit any secrets / API Keys (use environment variables)

**Comment by pgebheim** [comment]
```
version: "3.3"

services:

  db:
    container_name: chainlink-db
    image: postgres
    networks:
      - link
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  node:
    container_name: chainlink-node
    image: smartcontract/chainlink:candidate-0.10.4-rc3
    command: local start -p /chainlink/.password -a /chainlink/.api
    networks:
      - link
    ports:
      - "6688:6688"
    environment:
      SESSION_TIMEOUT: 15h0m0s
      ROOT: /chainlink
      LOG_LEVEL: debug
      ETH_CHAIN_ID: 42
      MIN_OUTGOING_CONFIRMATIONS: 2
      LINK_CONTRACT_ADDRESS: 0xa36085F69e2889c224210F603D836748e7dC0088
      CHAINLINK_PORT: "6688"
      SECURE_COOKIES: "false"
      GAS_UPDATER_ENABLED: "true"
      ALLOW_ORIGINS: "*"
      ETH_URL: wss://kovan.infura.io/ws/v3/96077a6214bb4800bb4e543f1e23e6e3
      DATABASE_URL: postgresql://postgres:password@db:5432/postgres?sslmode=disable
      CLIENT_NODE_URL: "http://localhost:6688"
    volumes:
      - "~/.chainlink-kovan:/chainlink"
    restart: always

  therundown-adapter:
    container_name: therundown-adapter
    image: therundown-adapter:0.0.2
    networks:
      - link
    ports:
      - "8080:8080"
    build:
      context: ~/projects/augur/external-adapters-js
      dockerfile: ./Dockerfile
      args:
        location: ./packages/sources/therundown
        package: "@chainlink/therundown-adapter"
      labels:
        com.chainlinklabs.external-adapter-type: sources
    environment:
      API_KEY: 5ecd3af15bmsh952587856928a56p18dc88jsne756975a0761

    
networks:
  link:
```
